AddButton = "Add an article"
HomeButton = "Back to home page"
LastModification = "Last modification"
ListOfArticles = "List of available articles:"
Login = "login"
Logout = "logout"
Register = "register"
Title = "Articles list"
User = "User"
