AddButton = "Add an article"
AdminPanel = "Admin Panel"
ArticleTitle = "Article Title"
BackToTop = "back to top"
BackToUsersList = "back to users list"
BinariesAndSC = "Binaries and source code of this software are available"
By = "by"
ChangePassButton = "Change password"
ChangeSettingsButton = "Change settings"
ChangeUserButton = "Change user"
ColorTheme = "color theme"
CurrentPass = "current password"
DeleteButton = "Delete"
Download = "Download"
EditButton = "Edit"
FromScratch = "or write it from scratch"
FullNameString = "full name"
Here = "here"
HomeButton = "Back to home page"
IsAdmin = "is admin?"
IsWriter = "is writer?"
Language = "language"
LastModification = "Last modification"
LicenseInformation = "License information"
ListOfArticles = "List of available articles:"
ListOfUsers = "List of registered users"
Login = "login"
LoginString = "login"
Logout = "logout"
ManagePortalUsers = "manage portal users"
ManageUser = "Manage user"
Misc = "Misc"
MustBeEmail = "Must be a valid e-mail address"
MustContain = "Must contain upcase, downcase, number and at least 8 characters"
NewPass = "new password"
NoArticles = "There is no articles here! Why don't you add one?"
OnlyLatin = "Only latin downcase letters and numbers"
PasswordString = "password"
Preview = "Preview"
ReNewPass = "retype new password"
Register = "register"
Security = "Security"
Settings = "Settings"
SubmitButton = "Submit"
SwitchModeButton = "Switch mode"
ThFullName = "Full name"
ThManage = "Manage"
ThName = "Name"
ThirdPartyLicenses = "Information about the licenses of the software used in the development of Grapho. The names of developers and organizations are not mentioned for the purpose of endorsing or promoting Grapho."
TitleAdmManageUser = "Admin panel | Manage user"
TitleAdmUsersList = "Admin panel | Users list"
TitleEdit = "Edit article"
TitleLicenses = "License information"
TitleLogin = "Log in form"
TitleMain = "Articles list"
TitleSignUp = "Sign up form"
TitleUploadArt = "Upload an article"
TitleUserSettings = "User settings"
UnderTerms = "under the terms of BSD 3-Clause License."
Upload = "Upload"
UploadAnArticle = "Upload an article"
UploadedBy = "Uploaded by"
User = "User"
UserStr = "user"
Writer = "Writer?"
loginButton = "Login"
save = "Save"
