AddButton = "Add an article"
ArticleTitle = "Article Title"
BackToTop = "back to top"
HomeButton = "Back to home page"
LastModification = "Last modification"
ListOfArticles = "List of available articles:"
Login = "login"
Logout = "logout"
Preview = "Preview"
Register = "register"
TitleAdmManageUser = "Admin panel | Manage user"
TitleAdmUsersList = "Admin panel | Users list"
TitleEdit = "Edit article"
TitleLogin = "Log in form"
TitleMain = "Articles list"
TitleSignUp = "Sign up form"
TitleUploadArt = "Upload an article"
TitleUserSettings = "User settings"
Upload = "Upload"
UploadedBy = "Uploaded by"
User = "User"
save = "Save"
