AddButton = "Add an article"
AdminPanel = "Admin Panel"
ArticleTitle = "Article Title"
BackToTop = "back to top"
BackToUsersList = "back to users list"
By = "by"
ChangePassButton = "Change password"
ChangeSettingsButton = "Change settings"
ChangeUserButton = "Change user"
ColorTheme = "color theme"
CurrentPass = "current password"
Download = "Download"
FullNameString = "full name"
HomeButton = "Back to home page"
IsAdmin = "is admin?"
Language = "language"
LastModification = "Last modification"
ListOfArticles = "List of available articles:"
ListOfUsers = "List of registered users"
Login = "login"
LoginString = "login"
Logout = "logout"
ManagePortalUsers = "manage portal users"
ManageUser = "Manage user"
Misc = "Misc"
MustBeEmail = "Must be a valid e-mail address"
MustContain = "Must contain upcase, downcase, number and at least 8 characters"
NewPass = "new password"
OnlyLatin = "Only latin downcase letters and numbers"
PasswordString = "password"
Preview = "Preview"
ReNewPass = "retype new password"
Register = "register"
Security = "Security"
Settings = "Settings"
SubmitButton = "Submit"
ThFullName = "Full name"
ThManage = "Manage"
ThName = "Name"
TitleAdmManageUser = "Admin panel | Manage user"
TitleAdmUsersList = "Admin panel | Users list"
TitleEdit = "Edit article"
TitleLogin = "Log in form"
TitleMain = "Articles list"
TitleSignUp = "Sign up form"
TitleUploadArt = "Upload an article"
TitleUserSettings = "User settings"
Upload = "Upload"
UploadedBy = "Uploaded by"
User = "User"
UserStr = "user"
loginButton = "Login"
save = "Save"
